### ISSUE TITLE
Request: Millenial Media SDK and Adapter Integration

### ISSUE THREAD

**Issue by designerkamal** [digicrafts/MoPub-ANE#1]
The ANE works good. Would be great if you can add the mmedia sdks too http://mmedia.com/?refsite=developer#developerHome

**Comment by digicrafts** [comment]
Will try to support it. Have some issue on Android side.

**Comment by khambadkone** [comment]
@digicrafts have you got it to work with MM in iOS?  are there any version dependencies with MoPub and MM SDKs?

**Comment by digicrafts** [comment]
@khambadkone If you want the IOS version, i can upload it tonight.

**Comment by khambadkone** [comment]
That would be great.

Are there specific versions of the MoPub or MM libraries we should be using?

**Comment by digicrafts** [comment]
The sdk is compiled into the ane. You can use other version sdk if you want to compile yourself.

Best,
william
on the go with my phone. d:)

**Comment by designerkamal** [comment]
+1 for the MM addition :)
