### ISSUE TITLE
Error #1065: Variable digicrafts.extensions::Mopub is not defined.

### ISSUE THREAD

**Issue by alanlanglois** [digicrafts/MoPub-ANE#4]
Hi, 
First of all Thx for the great job you've done on it. I'm not a newbie regarding ANE, I've already worked with several without any problem. 
I'm using FlashDevelop and I get this error when I try to compile my app (on desktop):
Error #1065: Variable digicrafts.extensions::Mopub is not defined
Maybe I'm missing something, but it sounds like if your ANE doesn't works exactly like the other ones I use. I usually follow these steps: 
https://plus.google.com/u/0/109524935899218597554/posts/7rhFEX7S372
But in you case and if I follow your steps, I don't need to add anything in my application.xml file on iOS. Is that correct?
Thx for your help :)

**Comment by alanlanglois** [comment]
UPDATE:: The lack of "isAvailable" methode is the cause of this error, I fixed it by checking the device type, if it's an iOS or Android device, I instanciate Mopub otherwise I just don't. It's kind of dirty, this ANE would deserve a better API and a desktop support (at least be able to compile from desktop even if the ad doesn't popup). 
Thx anyway, it works fine so far on iOS :)

**Comment by tsangwailam** [comment]
Sorry for late reply. Will add isSupported property for checking.
